### ISSUE TITLE
Options are not be saved + styles of theme stick

### ISSUE THREAD

**Issue by nextgenthemes** [apfelbox/Prism-Detached#4]
Any when I click save on the options page nothing gets saved and everything just resets after pushing save.

Also my theme has the `.entry-content code { background-color: #333; }` style with sticks and looks unreadable with prism styles. The should be some kind if style reset for that.

Look here, password = 1 http://nextgenthemes.com/2013/09/fail-wp_nav_menu-code/

Btw: wasn't php added as a supported language to PRISM? If yes it should be mentioned (in options page)

**Comment by apfelbox** [comment]
> Any when I click save on the options page nothing gets saved and everything just resets after pushing save.

Did you notice that there are two save buttons? "Save theme" and "Save Extensions"?

> Also my theme has the .entry-content code { background-color: #333; } style with sticks and looks unreadable with prism styles. The should be some kind if style reset for that.

This plugin is just a wrapper around the Prism library. So if there is a problem with the themes, you can report it upstream (in the [prism repo](https://github.com/LeaVerou/prism)) - it will be included automatically in this plugin then too.

> Btw: wasn't php added as a supported language to PRISM? If yes it should be mentioned (in options page)

It is:
![Prism Core Supported languages](http://i.imgur.com/b1Stajp.png)

**Comment by legomushroom** [comment]
doesn't save settings for me too. I have just one save button on plugin settings page http://take.ms/ch91b

**Comment by legomushroom** [comment]
I've figured it out. Looks like when you installing the plugin thru wp plugins search, _admin_settings.php_ is differs from that you have in this repo, so it is fails. Take a look at my previous comment for the screenshot.

**Comment by apfelbox** [comment]
Ok thanks, I will take a look at it (and probably need to release a new version on wp plugins).

**Comment by nextgenthemes** [comment]
7 months later ... sorry for not replying earlier. But it would not be that hard to figure out the what the version on wp.org is doing. Instead you screenshoted your dev version, how should this help? It is indeed to this day still displaying 4 languages on the options page, no two different save buttons and does not save any options.

And yet again one month passed by and you do not looked into it. I had to write a negative review based on this not willing to maintain his correctly on wp.org.

**Comment by apfelbox** [comment]
Maintining it on wp.org is a huge pain, unfortunately.
Nevertheless: I will update the plugin for 3.9 (if necessary) and include the current version of Prism (even on wp.org :wink:). I will take a look at your issue then, too.
