### ISSUE TITLE
Syntax error installing

### ISSUE THREAD

**Issue by genericmoniker** [apfelbox/Prism-Detached#5]
I just downloaded from the official WP plugins (from within the WordPress UI) and tried to activate and got:

Parse error: syntax error, unexpected T_FUNCTION, expecting ')' in /home/content/e/s/m/esmithynet/html/wp-content/plugins/prism-detached/Prism_Detached.php on line 97

WordPress 3.6.1.

**Comment by apfelbox** [comment]
You need PHP 5.3+ to use Prism Detached.
